#!/usr/bin/with-contenv bash
# shellcheck shell=bash

# Define bash colours
NOCOLOR='\033[0m'
#LIGHTRED='\033[1;31m'
#CYAN='\033[0;36m'
YELLOW='\033[1;33m'

# Set up timezone
if [ -z "${TZ}" ]; then
  echo "${YELLOW}WARNING: TZ environment variable not set${NOCOLOR}"
else
  ln -snf "/usr/share/zoneinfo/$TZ" /etc/localtime && echo "$TZ" > /etc/timezone
fi
